const LABELS={sun:'Güneş',moon:'Ay',ascendant:'Yükselen',mercury:'Merkür',venus:'Venüs',mars:'Mars',jupiter:'Jüpiter',saturn:'Satürn',uranus:'Uranüs',neptune:'Neptün',pluto:'Plüton',north_node:'Kuzey Ay Düğümü',mc:'MC'};
const SIGNS=['Koç','Boğa','İkizler','Yengeç','Aslan','Başak','Terazi','Akrep','Yay','Oğlak','Kova','Balık'];
const SECTIONS=[['profilin','> ## • PROFİLİN •'],['haritanin_ozu','> ## • HARİTANIN ÖZÜ •'],['para_kariyer','> ## • PARA & KARİYER •'],['iliskiler','> ## • İLİŞKİLER •'],['aile','> ## • AİLE •'],['karmalar','> ## • KARMALAR •']];
const tok=s=>(s.toLocaleLowerCase('tr-TR').match(/[\p{L}\p{N}]+/gu)||[]);
const norm=s=>tok(s).join(' ');
const set=s=>new Set(s);
const jac=(a,b)=>{const i=[...a].filter(x=>b.has(x)).length,u=new Set([...a,...b]).size;return u?i/u:0};
const tris=s=>{const t=tok(s),r=[];for(let i=0;i+2<t.length;i++)r.push(`${t[i]} ${t[i+1]} ${t[i+2]}`);return set(r)};
const contain=(a,b)=>{if(!a.size||!b.size)return 0;return [...a].filter(x=>b.has(x)).length/Math.min(a.size,b.size)};
const count=(s,n)=>s.split(n).length-1;
function bodyOf(out,mark){const l=out.split('\n'),a=l.indexOf(mark);if(a<0)return null;let x=l.indexOf('---',a+1);if(x<0)return null;let y=l.indexOf('---',x+1);return y<0?null:l.slice(x+1,y).join('\n').trim()}
function pmap(ev){return new Map(ev.filter(x=>x.kind==='placement').map(x=>[x.subject_id,x]))}
function pline(x){return `> *${LABELS[x.subject_id]} ${x.sign} ${x.degree}${x.house?` — ${x.house}`:''}${x.retrograde?' (R)':''}*`}
function claims(s){const c=[],amb=[];for(const z of s.split(/(?<=[.!?])\s+|\n+/u).map(x=>x.trim()).filter(Boolean)){const su=Object.entries(LABELS).filter(([,l])=>z.includes(l)).map(([id])=>id),sg=SIGNS.filter(x=>z.includes(x));if(su.length===1&&sg.length===1)c.push({subject_id:su[0],sign:sg[0],sentence:z});else if(su.length&&sg.length)amb.push({subjects:su,signs:sg,sentence:z})}return {c,amb}}
export function anchorScore(s,ev,subjects){const m=pmap(ev),{c}=claims(s),hit=new Set;for(const q of c){if(subjects.includes(q.subject_id)&&m.get(q.subject_id)?.sign===q.sign)hit.add(q.subject_id)}return {score:hit.size,matched:[...hit].sort()}}
const producer=d=>['contradiction','specificity','repetition','section_distinction','counterexample_specificity'].includes(d)?{layer:'model_semantic_generation',proven:true,basis:'Failure is inside model-owned section body text; accepted canonical renderer preserves body paragraphs verbatim and production provenance is rechecked before the run.'}:d==='canonical_language'?{layer:'canonical_renderer_or_delivery_surface',proven:false,basis:'Visible canonical markers are renderer-owned; deeper producer proof would be required before any production revision.'}:{layer:'unknown',proven:false,basis:'No frozen producer mapping.'};
export {producer};
export function evaluate(out,ev,r){const d={},pf=[],mk=r.canonical_language.required_markers_exact_once_in_order,mc=Object.fromEntries(mk.map(x=>[x,count(out,x)]));let ordered=true,cur=-1;for(const x of mk){const a=out.indexOf(x);if(a<0||a<=cur){ordered=false;break}cur=a}const forbidden=r.canonical_language.forbidden_visible_tokens.filter(x=>out.includes(x));const cp=out.startsWith(r.canonical_language.required_prefix)&&Object.values(mc).every(x=>x===1)&&ordered&&!forbidden.length;d.canonical_language={verdict:cp?'PASS':'FAIL',required_prefix_ok:out.startsWith(r.canonical_language.required_prefix),markers_exact_once:Object.values(mc).every(x=>x===1),markers_in_order:ordered,forbidden_visible_tokens:forbidden};if(!cp)pf.push({dimension:'canonical_language',...producer('canonical_language')});
 const pm=pmap(ev),pcs=[...pm.values()].map(x=>({subject_id:x.subject_id,line:pline(x),count:count(out,pline(x))}));const bodies={};let unparse=false;for(const [id,m] of SECTIONS){const b=bodyOf(out,m);if(b===null)unparse=true;bodies[id]=b||''}const joined=Object.values(bodies).join('\n\n'),{c,amb}=claims(joined),bad=c.filter(q=>pm.get(q.subject_id)&&pm.get(q.subject_id).sign!==q.sign),pex=pcs.every(x=>x.count===1);
 if(unparse)d.contradiction={verdict:'UNKNOWN',reason:'REQUIRED_SECTION_BODY_UNPARSABLE',placement_checks:pcs};else{const p=pex&&bad.length<=r.contradiction.max_direct_body_planet_sign_contradictions;d.contradiction={verdict:p?'PASS':'FAIL',placement_lines_exactly_once:pex,direct_body_contradictions:bad,ambiguous_claims_not_scored:amb.length};if(!p){if(!pex)pf.push({dimension:'contradiction',layer:'validated_contract_or_renderer_surface',proven:false,basis:'A canonical placement line diverged from verified evidence; deeper producer proof is required.'});if(bad.length>r.contradiction.max_direct_body_planet_sign_contradictions)pf.push({dimension:'contradiction',...producer('contradiction')})}}
 const a=anchorScore(joined,ev,r.specificity.anchor_subjects),sw=Object.fromEntries(Object.entries(bodies).map(([id,b])=>[id,tok(b).length])),tw=tok(joined).length;if(unparse)d.specificity={verdict:'UNKNOWN',reason:'REQUIRED_SECTION_BODY_UNPARSABLE'};else{const p=a.score>=r.specificity.minimum_distinct_correct_body_anchors&&tw>=r.specificity.minimum_total_body_words&&Object.values(sw).every(x=>x>=r.specificity.minimum_required_section_words);d.specificity={verdict:p?'PASS':'FAIL',correct_body_anchor_score:a.score,matched_anchor_subjects:a.matched,total_body_words:tw,required_section_words:sw};if(!p)pf.push({dimension:'specificity',...producer('specificity')})}
 const ids=Object.keys(bodies),dups=[],low=[];let mt=0,mj=0;for(let i=0;i<ids.length;i++){const x=ids[i],n=set(tok(bodies[x])).size;if(n<r.section_distinction.minimum_distinct_tokens_per_required_section)low.push({section:x,distinct_tokens:n});for(let j=i+1;j<ids.length;j++){const y=ids[j];if(norm(bodies[x])&&norm(bodies[x])===norm(bodies[y]))dups.push([x,y]);mt=Math.max(mt,contain(tris(bodies[x]),tris(bodies[y])));mj=Math.max(mj,jac(set(tok(bodies[x])),set(tok(bodies[y]))))}}
 if(unparse){d.repetition={verdict:'UNKNOWN',reason:'REQUIRED_SECTION_BODY_UNPARSABLE'};d.section_distinction={verdict:'UNKNOWN',reason:'REQUIRED_SECTION_BODY_UNPARSABLE'}}else{const rp=dups.length<=r.repetition.max_exact_duplicate_required_section_bodies&&mt<=r.repetition.max_pairwise_body_trigram_containment;d.repetition={verdict:rp?'PASS':'FAIL',exact_duplicate_section_pairs:dups,max_pairwise_body_trigram_containment:+mt.toFixed(4)};if(!rp)pf.push({dimension:'repetition',...producer('repetition')});const sp=mj<=r.section_distinction.max_pairwise_required_section_token_jaccard&&!low.length;d.section_distinction={verdict:sp?'PASS':'FAIL',max_pairwise_required_section_token_jaccard:+mj.toFixed(4),low_distinct_sections:low};if(!sp)pf.push({dimension:'section_distinction',...producer('section_distinction')})}
 return {dimensions:d,producer_failures:pf,combinedBody:joined,anchor:a};}
export function aggregate(v){return v.includes('FAIL')?'FAIL':v.includes('BLOCKED')?'BLOCKED':v.includes('UNKNOWN')?'UNKNOWN':'PASS'}
